// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/radio_calibration/radio_calibration.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include "plugin_base.h"

namespace mavsdk {

class System;
class RadioCalibrationImpl;

/**
 * @brief Enable to calibrate sensors of a drone such as gyro, accelerometer, and magnetometer.
 */
class RadioCalibration : public PluginBase {
public:
    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto radio_calibration = RadioCalibration(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit RadioCalibration(System& system); // deprecated

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto radio_calibration = RadioCalibration(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit RadioCalibration(std::shared_ptr<System> system); // new

    /**
     * @brief Destructor (internal use only).
     */
    ~RadioCalibration();






    /**
     * @brief Possible results returned for calibration commands
     */
    enum class Result {
        Unknown, /**< @brief Unknown result. */
        Success, /**< @brief The calibration succeeded. */
        Next, /**< @brief Intermediate message showing progress or instructions on the next steps. */
        Failed, /**< @brief Calibration failed. */
        NoSystem, /**< @brief No system is connected. */
        ConnectionError, /**< @brief Connection error. */
        Busy, /**< @brief Vehicle is busy. */
        CommandDenied, /**< @brief Command refused by vehicle. */
        Timeout, /**< @brief Command timed out. */
        Cancelled, /**< @brief Calibration process was cancelled. */
        FailedArmed, /**< @brief Calibration process failed since the vehicle is armed. */
    };

    /**
     * @brief Stream operator to print information about a `RadioCalibration::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, RadioCalibration::Result const& result);





    /**
     * @brief Progress data coming from calibration.
     *
     * Can be a progress percentage, or an instruction text.
     */
    struct ProgressData {
        
        bool has_progress{false}; /**< @brief Whether this ProgressData contains a 'progress' status or not */
        float progress{float(NAN)}; /**< @brief Progress (percentage) */
        bool has_status_text{false}; /**< @brief Whether this ProgressData contains a 'status_text' or not */
        std::string status_text{}; /**< @brief Instruction text */
    };

    /**
     * @brief Equal operator to compare two `RadioCalibration::ProgressData` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const RadioCalibration::ProgressData& lhs, const RadioCalibration::ProgressData& rhs);

    /**
     * @brief Stream operator to print information about a `RadioCalibration::ProgressData`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, RadioCalibration::ProgressData const& progress_data);


    /**
     * @brief Callback type for asynchronous RadioCalibration calls.
     */
    using ResultCallback = std::function<void(Result)>;




        
    /**
    * @brief Callback type for calibrate_radio_async.
    */
        
    using CalibrateRadioCallback = std::function<void(RadioCalibration::Result, ProgressData)>;

    /**
     * @brief Perform radio calibration.
     */
    void calibrate_radio_async(CalibrateRadioCallback callback);








    /**
     * @brief Cancel ongoing calibration process.
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    void cancel() const;




    /**
     * @brief Copy constructor.
     */
    RadioCalibration(const RadioCalibration& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const RadioCalibration& operator=(const RadioCalibration&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<RadioCalibrationImpl> _impl;
};

} // namespace mavsdk